Repository tensorflow/tflite-micro, pull requests merged in 2021-06, with the labels that each got.

#104 Updated sync and use of shared TFL/TFLM code.
  ci/sync_from_upstream_tf.sh
  tensorflow/lite/micro/tools/make/Makefile
Labels: ci:run, cla: yes

#114 Sync reference implementation of SPACE_TO_DEPTH from lite
  ci/sync_from_upstream_tf.sh
Labels: ci:run, cla: yes

#115 Integrate the HiFi 5 Neural Network Library v1.5.0
  tensorflow/lite/micro/kernels/xtensa/quantize.cc
  tensorflow/lite/micro/kernels/xtensa/svdf.cc
  tensorflow/lite/micro/kernels/xtensa/xtensa.h
  tensorflow/lite/micro/tools/make/ext_libs/xtensa.inc
Labels: ci:run, cla: yes

#112 tools to check in json value files from ci
  .github/assets/write_json.py
  .github/workflows/ci-test.yml
Labels: cla: yes

#124 Disable currently failing test to make the Xtensa build green.
  tensorflow/lite/micro/examples/micro_speech/Makefile.inc
  tensorflow/lite/micro/kernels/xtensa/svdf.cc
  tensorflow/lite/micro/kernels/xtensa/xtensa.h
Labels: ci:run, cla: yes

#125 Add Xtensa toolchain github workflow.
  .github/workflows/xtensa.yml
  tensorflow/lite/micro/tools/ci_build/test_xtensa_fusion_f1.sh
Labels: ci:run, ci:test, cla: yes

#126 Attempt to fix the xtensa workflow.
  .github/workflows/xtensa.yml
Labels: cla: yes

#130 Fixes for Xtensa workflow.
  .github/workflows/xtensa.yml
  tensorflow/lite/micro/tools/ci_build/test_xtensa_fusion_f1.sh
Labels: cla: yes

#127 Revert https://github.com/tensorflow/tensorflow/pull/47935
  tensorflow/lite/experimental/microfrontend/lib/BUILD
  tensorflow/lite/experimental/microfrontend/lib/fft_io.c
  tensorflow/lite/experimental/microfrontend/lib/fft_util.cc
  tensorflow/lite/experimental/microfrontend/lib/filterbank_io.c
  tensorflow/lite/experimental/microfrontend/lib/filterbank_util.c
  tensorflow/lite/experimental/microfrontend/lib/fprintf_shim.h
  tensorflow/lite/experimental/microfrontend/lib/frontend_io.c
  tensorflow/lite/experimental/microfrontend/lib/frontend_main.c
  tensorflow/lite/experimental/microfrontend/lib/frontend_memmap_generator.c
  tensorflow/lite/experimental/microfrontend/lib/frontend_memmap_main.c
  tensorflow/lite/experimental/microfrontend/lib/frontend_util.c
  tensorflow/lite/experimental/microfrontend/lib/log_scale_io.c
  tensorflow/lite/experimental/microfrontend/lib/memory_util.h
  tensorflow/lite/experimental/microfrontend/lib/memory_util_fixed_pool.c
  tensorflow/lite/experimental/microfrontend/lib/memory_util_stdlib.c
  tensorflow/lite/experimental/microfrontend/lib/memory_util_test.cc
  tensorflow/lite/experimental/microfrontend/lib/noise_reduction_io.c
  tensorflow/lite/experimental/microfrontend/lib/noise_reduction_util.c
  tensorflow/lite/experimental/microfrontend/lib/pcan_gain_control.c
  tensorflow/lite/experimental/microfrontend/lib/pcan_gain_control_util.c
  tensorflow/lite/experimental/microfrontend/lib/window_io.c
  tensorflow/lite/experimental/microfrontend/lib/window_util.c
  tensorflow/lite/micro/examples/micro_speech/Makefile.inc
  tensorflow/lite/micro/examples/micro_speech/simple_features/bluepill/simple_features_generator_test.cc
  tensorflow/lite/micro/tools/make/targets/bluepill_makefile.inc
Labels: ci:run, cla: yes

#131 Add status badge for the Xtensa workflow.
  README.md
Labels: cla: yes

#129 Have the project generation script explicitly call make third_party_downloads.
  .github/workflows/ci.yml
  tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py
Labels: ci:run, cla: yes

#134 Add files from TfLite
  ci/sync_from_upstream_tf.sh
Labels: ci:run, cla: yes

#138 Update .gitignore for vscode
  .gitignore
Labels: ci:run, cla: yes

#142 change special case logic for music-break model
  tensorflow/lite/micro/kernels/circular_buffer.cc
Labels: ci:run, cla: yes

#109 Revert "Revert: PR #48758: TFLM: Remove uint8 support for CMSIS-NN ke…
  tensorflow/lite/micro/examples/network_tester/README.md
  tensorflow/lite/micro/examples/network_tester/expected_output_data.h
  tensorflow/lite/micro/examples/network_tester/input_data.h
  tensorflow/lite/micro/examples/network_tester/network_model.h
  tensorflow/lite/micro/examples/network_tester/network_tester_test.cc
  tensorflow/lite/micro/kernels/add.cc
  tensorflow/lite/micro/kernels/add_test.cc
  tensorflow/lite/micro/kernels/circular_buffer.cc
  tensorflow/lite/micro/kernels/cmsis_nn/add.cc
  tensorflow/lite/micro/kernels/cmsis_nn/conv.cc
  tensorflow/lite/micro/kernels/cmsis_nn/depthwise_conv.cc
  tensorflow/lite/micro/kernels/cmsis_nn/mul.cc
  tensorflow/lite/micro/kernels/cmsis_nn/pooling.cc
  tensorflow/lite/micro/kernels/cmsis_nn/softmax.cc
  tensorflow/lite/micro/kernels/depthwise_conv.cc
  tensorflow/lite/micro/kernels/depthwise_conv_common.cc
  tensorflow/lite/micro/kernels/detection_postprocess_test.cc
  tensorflow/lite/micro/kernels/mul.cc
  tensorflow/lite/micro/kernels/mul_test.cc
  tensorflow/lite/micro/kernels/pooling.cc
  tensorflow/lite/micro/kernels/pooling_test.cc
Labels: ci:run, cla: yes

#155 Additional bug fix for CreateWritableTensorDimsWithCopy
  tensorflow/lite/micro/kernels/kernel_util.cc
Labels: ci:run, cla: yes

#154 Bug fix for TfLiteTensor dims
  tensorflow/lite/micro/micro_allocator.cc
Labels: ci:run, cla: yes

#144 Remove -Wno-strict-aliasing
  tensorflow/lite/micro/tools/make/ext_libs/cmsis_nn.inc
  tensorflow/lite/micro/tools/make/ext_libs/stm32_bare_lib.patch
  tensorflow/lite/micro/tools/make/ext_libs/stm32_bare_lib_download.sh
  tensorflow/lite/micro/tools/make/targets/bluepill_makefile.inc
  tensorflow/lite/micro/tools/make/targets/cortex_m_corstone_300_makefile.inc
  tensorflow/lite/micro/tools/make/targets/cortex_m_generic_makefile.inc
  tensorflow/lite/micro/tools/make/targets/stm32f4_makefile.inc
Labels: ci:run, cla: yes

#156 Fix the style check docker container.
  .github/workflows/ci.yml
  ci/Dockerfile.micro
Labels: ci:run, cla: yes

#165 gitignore all files and directories with google in the name.
  .gitignore
Labels: ci:run, cla: yes

#171 Fix broken image links in pre-allocated tensors RFC
  tensorflow/lite/micro/docs/rfc/001_preallocated_tensors.md
Labels: ci:run, cla: yes

#173 Manually creating a git repo for Pigweed checks is no longer necessary.
  tensorflow/lite/micro/tools/ci_build/test_code_style.sh
Labels: ci:run, cla: yes

#160 Add Hexagon optimized kernels.
  tensorflow/lite/micro/tools/ci_build/test_code_style.sh
  tensorflow/lite/micro/tools/make/Makefile
  tensorflow/lite/micro/tools/make/ext_libs/hexagon.inc
  tensorflow/lite/micro/tools/make/specialize_files.py
  tensorflow/lite/micro/tools/make/targets/hexagon/download_hexagon.sh
  third_party/hexagon/LICENSE
  third_party/hexagon/fully_connected.cc
  third_party/hexagon/hexagon_tflm_translation_fully_connected.h
  third_party/hexagon/hexagon_tflm_translation_svdf.h
  third_party/hexagon/svdf.cc
Labels: ci:run, cla: yes

#150 remove ci runner labels from PRs
  .github/workflows/ci.yml
  .github/workflows/remove-labels.yml
Labels: ci:run, cla: yes

#176 Wrap Flexbuffer methods to avoid inlining.
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/circular_buffer.cc
  tensorflow/lite/micro/kernels/detection_postprocess.cc
  tensorflow/lite/micro/kernels/kernel_util.cc
  tensorflow/lite/micro/kernels/kernel_util.h
Labels: cla: yes

#168 Separate core, kernel and third party objects.
  tensorflow/lite/micro/examples/micro_speech/apollo3/Makefile.inc
  tensorflow/lite/micro/tools/ci_build/test_bluepill.sh
  tensorflow/lite/micro/tools/make/Makefile
  tensorflow/lite/micro/tools/make/helper_functions.inc
Labels: cla: yes

#169 Add int8 conv kernel variant for xtensa
  tensorflow/lite/micro/benchmarks/person_detection_benchmark.cc
  tensorflow/lite/micro/kernels/conv.h
  tensorflow/lite/micro/kernels/conv_test.h
  tensorflow/lite/micro/kernels/micro_ops.h
  tensorflow/lite/micro/kernels/xtensa/conv.cc
  tensorflow/lite/micro/kernels/xtensa/conv_hifi.cc
  tensorflow/lite/micro/kernels/xtensa/conv_int8_reference.cc
  tensorflow/lite/micro/kernels/xtensa/xtensa_conv.h
  tensorflow/lite/micro/micro_mutable_op_resolver.h
  tensorflow/lite/micro/tools/make/ext_libs/xtensa.inc
Labels: cla: yes

#181 Add to include path for hexagon builds with the downloaded hexagon kernels.
  tensorflow/lite/micro/tools/make/targets/hexagon_makefile.inc
Labels: cla: yes

#178 Explicitly use python3 from the Makefile.
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes

#183 Remove reference to ConvReferencePrepareInt8
  tensorflow/lite/micro/kernels/xtensa/conv_hifi.cc
  tensorflow/lite/micro/kernels/xtensa/xtensa_conv.h
Labels: cla: yes

#184 Fix #182 by explicitly checking out pull_request.head.sha
  .github/workflows/xtensa.yml
Labels: cla: yes

#179 Update visibility to include all folders in the repository.
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/testing/BUILD
Labels: cla: yes

#191 Update top-level readme
  README.md
  tensorflow/lite/micro/README.md
Labels: cla: yes

#192 remove old files.
  tensorflow/lite/micro/CONTRIBUTING.md
  tensorflow/lite/micro/README.md
Labels: cla: yes

#186 dockerfile for hexagon testing tools
  ci/Dockerfile.hexagon
Labels: cla: yes

#194 Remove `build_test` from the BUILD files.
  tensorflow/lite/micro/benchmarks/BUILD
  tensorflow/lite/micro/kernels/test_data_generation/BUILD
Labels: cla: yes

#175 Add Arm Compiler 6 support to Corstone-300 target
  tensorflow/lite/micro/cortex_m_corstone_300/README.md
  tensorflow/lite/micro/tools/make/Makefile
  tensorflow/lite/micro/tools/make/ethos_u_core_platform_download.sh
  tensorflow/lite/micro/tools/make/targets/cortex_m_corstone_300_makefile.inc
Labels: cla: yes

#196 Explicitly build all targets with bazel as part of CI.
  tensorflow/lite/micro/tools/ci_build/test_bazel.sh
Labels: cla: yes

#198 Remove hifimini support from the bazel build.
  tensorflow/lite/micro/BUILD
  tensorflow/lite/micro/benchmarks/BUILD
  tensorflow/lite/micro/kernels/BUILD
Labels: cla: yes

#200 Workaround for Corstone-300 target
  tensorflow/lite/micro/tools/make/targets/cortex_m_corstone_300_makefile.inc
Labels: cla: yes

#189 Update ethosu driver entrypoint
  tensorflow/lite/micro/cortex_m_corstone_300/system_setup.cc
  tensorflow/lite/micro/kernels/ethos_u/ethosu.cc
  tensorflow/lite/micro/tools/make/third_party_downloads.inc
Labels: cla: yes

#117 Port the SPACE_TO_DEPTH operator from lite to micro
  tensorflow/lite/kernels/internal/reference/space_to_depth.h
  tensorflow/lite/micro/all_ops_resolver.cc
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/micro_ops.h
  tensorflow/lite/micro/kernels/space_to_depth.cc
  tensorflow/lite/micro/kernels/space_to_depth_test.cc
  tensorflow/lite/micro/micro_mutable_op_resolver.h
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes

#206 Refactor reference implementation of pooling.cc
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/cmsis_nn/pooling.cc
  tensorflow/lite/micro/kernels/micro_ops.h
  tensorflow/lite/micro/kernels/pooling.cc
  tensorflow/lite/micro/kernels/pooling.h
  tensorflow/lite/micro/kernels/pooling_common.cc
  tensorflow/lite/micro/kernels/pooling_test.cc
  tensorflow/lite/micro/micro_mutable_op_resolver.h
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes

#187 check PR description for a BUG= line
  .github/workflows/check_pr_has_bug.yml
  CONTRIBUTING.md
Labels: cla: yes

#211 Change job name and remove trailing whitespace.
  .github/workflows/check_pr_has_bug.yml
  .github/workflows/ci.yml
Labels: ci:run, cla: yes

#212 Fix the Vision P6 build.
  tensorflow/lite/micro/kernels/xtensa/conv.cc
  tensorflow/lite/micro/kernels/xtensa/xtensa_conv.h
Labels: cla: yes

#207 Add support for 8x16 kernels in TFLM.
  tensorflow/lite/micro/kernels/cmsis_nn/conv.cc
  tensorflow/lite/micro/kernels/concatenation.cc
  tensorflow/lite/micro/kernels/concatenation_test.cc
  tensorflow/lite/micro/kernels/conv.cc
  tensorflow/lite/micro/kernels/conv_common.cc
  tensorflow/lite/micro/kernels/conv_test.cc
  tensorflow/lite/micro/kernels/conv_test.h
  tensorflow/lite/micro/kernels/conv_test_common.cc
  tensorflow/lite/micro/kernels/leaky_relu.cc
  tensorflow/lite/micro/kernels/leaky_relu_test.cc
  tensorflow/lite/micro/kernels/reshape_test.cc
  tensorflow/lite/micro/kernels/strided_slice.cc
  tensorflow/lite/micro/kernels/strided_slice_test.cc
  tensorflow/lite/micro/kernels/sub.cc
  tensorflow/lite/micro/kernels/sub_test.cc
  tensorflow/lite/micro/kernels/transpose_conv.cc
  tensorflow/lite/micro/kernels/transpose_conv_test.cc
  tensorflow/lite/micro/micro_utils.h
  tensorflow/lite/micro/test_helpers.cc
  tensorflow/lite/micro/test_helpers.h
Labels: cla: yes

#215 Add BUG=<reason> to sync PR description (required after #187)
  .github/workflows/sync.yml
Labels: cla: yes

#219 - Add missing default build rules for .c and .S files
  tensorflow/lite/micro/tools/make/Makefile
  tensorflow/lite/micro/tools/make/ext_libs/hexagon.inc
Labels: cla: yes

#223 Allow specialize_files to be given an invalid directory.
  tensorflow/lite/micro/tools/make/specialize_files.py
Labels: cla: yes

#221 Updated QC implementation no longer needs additional arena for keyword_benchmark.
  tensorflow/lite/micro/benchmarks/keyword_benchmark.cc
Labels: cla: yes

#220 Support 16-bit add kernel
  tensorflow/lite/micro/kernels/add.cc
  tensorflow/lite/micro/kernels/add_test.cc
  tensorflow/lite/micro/kernels/cmsis_nn/add.cc
  tensorflow/lite/micro/kernels/cmsis_nn/pooling.cc
  tensorflow/lite/micro/kernels/quantize_common.cc
  tensorflow/lite/micro/kernels/quantize_test.cc
  tensorflow/lite/micro/kernels/transpose_conv.cc
  tensorflow/lite/micro/kernels/transpose_conv_test.cc
  tensorflow/lite/micro/test_helpers.cc
  tensorflow/lite/micro/test_helpers.h
Labels: cla: yes

#222 Add a way to get the interpreter from a benchmark runner.
  tensorflow/lite/micro/benchmarks/micro_benchmark.h
Labels: cla: yes

#240 Automatically include internal examples
  tensorflow/lite/micro/tools/make/Makefile
  tensorflow/lite/micro/tools/make/targets/bluepill_makefile.inc
Labels: cla: yes

#225 Up the maximum number of profiled events to 1024
  tensorflow/lite/micro/micro_profiler.h
Labels: cla: yes
