Repository tensorflow/tflite-micro, pull requests merged in 2021-12, with the labels that each got.

#735 Removing ARC related parts from examples' README files and fixes for ARC README files.
  tensorflow/lite/micro/examples/micro_speech/README.md
  tensorflow/lite/micro/examples/person_detection/README.md
  tensorflow/lite/micro/kernels/arc_mli/README.md
  tensorflow/lite/micro/tools/make/targets/arc/README.md
Labels: cla: yes, ci:mergify

#751 For both MicroAllocator and RecordingMicroAllocator, define function to return the default tail usage.
  tensorflow/lite/micro/memory_arena_threshold_test.cc
  tensorflow/lite/micro/micro_allocator.cc
  tensorflow/lite/micro/micro_allocator.h
  tensorflow/lite/micro/micro_allocator_test.cc
  tensorflow/lite/micro/recording_micro_allocator.cc
  tensorflow/lite/micro/recording_micro_allocator.h
Labels: cla: yes

#723 bugfix for CEVA-DSP fully connected glue code
  tensorflow/lite/micro/kernels/ceva/fully_connected.cc
Labels: cla: yes, ci:mergify

#752 Add script for getting the size of a binary built for the Xtensa
  tensorflow/lite/micro/testing/size_xtensa_binary.sh
  tensorflow/lite/micro/tools/make/targets/xtensa_makefile.inc
Labels: cla: yes

#731 Updated add kernel to fix build.
  tensorflow/lite/micro/kernels/arc_mli/add.cc
Labels: cla: yes

#759 Update HiFi4 nnlib to v2.5.0 from v2.4.1
  tensorflow/lite/micro/kernels/xtensa/quantize.cc
  tensorflow/lite/micro/tools/make/ext_libs/xa_nnlib_hifi4.patch
  tensorflow/lite/micro/tools/make/ext_libs/xtensa_download.sh
Labels: cla: yes

#755 Add integration test generation support for multiple inputs and types
  .github/workflows/generate_integration_tests.yml
  tensorflow/lite/micro/integration_tests/BUILD
  tensorflow/lite/micro/integration_tests/generate_per_layer_tests.py
  tensorflow/lite/micro/integration_tests/seanet/transpose_conv/integration_tests.cc
  tensorflow/lite/micro/integration_tests/templates/BUILD.mako
  tensorflow/lite/micro/integration_tests/templates/integration_tests_cc.mako
  tensorflow/lite/micro/tools/ci_build/test_generate_integration_tests.sh
Labels: cla: yes

#729 Bug fixes in mli_interface and mli_tf_utils.
  tensorflow/lite/micro/kernels/arc_mli/mli_interface.cc
  tensorflow/lite/micro/kernels/arc_mli/mli_tf_utils.h
Labels: cla: yes

#737 Removing ARC code related to examples and updating make files and test scripts.
  tensorflow/lite/micro/kernels/arc_mli/conv_slicing_test.cc
  tensorflow/lite/micro/kernels/arc_mli/depthwise_conv_slicing_test.cc
  tensorflow/lite/micro/kernels/arc_mli/fully_connected_slicing_test.cc
  tensorflow/lite/micro/kernels/arc_mli/pooling_slicing_test.cc
  tensorflow/lite/micro/testing/test_with_arc_mdb.sh
  tensorflow/lite/micro/tools/ci_build/test_arc.sh
  tensorflow/lite/micro/tools/make/ext_libs/arc_mli.inc
  tensorflow/lite/micro/tools/make/targets/arc/adaptation_tool.py
  tensorflow/lite/micro/tools/make/targets/arc/arc_common.inc
  tensorflow/lite/micro/tools/make/targets/arc/emsdp/emsdp.lcf
  tensorflow/lite/micro/tools/make/targets/arc/emsdp/emsdp_v2.lcf
  tensorflow/lite/micro/tools/make/targets/arc_custom_makefile.inc
  tensorflow/lite/micro/tools/make/targets/arc_emsdp_makefile.inc
  tensorflow/lite/micro/tools/make/third_party_downloads.inc
Labels: cla: yes

#726 Updated conv kernel to use function specializations and bug fixes for ARC.
  tensorflow/lite/micro/kernels/arc_mli/conv.cc
  tensorflow/lite/micro/kernels/arc_mli/mli_function_specializations.h
Labels: cla: yes

#734 Added micro_speech_mock example files for create_tflm_tree.py script.
  tensorflow/lite/micro/examples/micro_speech/Makefile.inc
Labels: cla: yes

#727 Updated fc kernel to use function specializations and bug fixes for ARC.
  tensorflow/lite/micro/kernels/arc_mli/fully_connected.cc
Labels: cla: yes

#728 Updated depthwise_conv kernel to use function specializations and bug fixes for ARC.
  tensorflow/lite/micro/kernels/arc_mli/depthwise_conv.cc
Labels: cla: yes

#768 Upload the script that geneartes the simple_add_model.tflite in models
  tensorflow/lite/micro/examples/memory_footprint/create_adder_model.py
  tensorflow/lite/micro/examples/memory_footprint/models/simple_add_model.tflite
Labels: ci:ready_to_merge

#801 Enable hifi4 internal for bazel configs (#781)
  tensorflow/lite/micro/kernels/BUILD
Labels: ci:ready_to_merge

#803 Disable test that takes > 5mins to run locally.
  third_party/xtensa/examples/micro_speech_lstm/Makefile.inc
Labels: ci:ready_to_merge

#798 Add a test to verify that MicroIntepreter::arena_used_bytes() provides a required arena size for the model to run
  tensorflow/lite/micro/micro_interpreter_test.cc
  tensorflow/lite/micro/test_helpers.cc
  tensorflow/lite/micro/test_helpers.h
  tensorflow/lite/micro/tools/make/renode.patch
  tensorflow/lite/micro/tools/make/renode_download.sh
  tensorflow/lite/micro/tools/make/targets/bluepill/bluepill.lds
  tensorflow/lite/micro/tools/make/targets/stm32f4/stm32f4.lds
Labels: ci:ready_to_merge

#730 Updated pooling kernel to use function specializations and bug fixes for ARC.
  tensorflow/lite/micro/kernels/arc_mli/pooling.cc
Labels: cla: yes, ci:ready_to_merge

#805 docs: Fix broken listing in contribution docs
  tensorflow/lite/micro/docs/optimized_kernel_implementations.md
Labels: ci:ready_to_merge

#704 Add Support for building Micropython using project generator
  tensorflow/lite/micro/tools/ci_build/test_project_generation.sh
  tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py
Labels: cla: yes, ci:ready_to_merge

#810 Disable micro_interpreter_test for FVP target
  tensorflow/lite/micro/tools/make/targets/cortex_m_corstone_300_makefile.inc
Labels: ci:ready_to_merge

#811 Revert optimized xtensa leaky relu kernel
  tensorflow/lite/micro/kernels/xtensa/leaky_relu.cc
  tensorflow/lite/micro/tools/ci_build/test_xtensa_hifi3z.sh
Labels: ci:ready_to_merge

#813 Allow zero points to be broadcasted during model initialization
  tensorflow/lite/micro/kernels/conv_common.cc
  tensorflow/lite/micro/micro_allocator.cc
Labels: ci:ready_to_merge

#814 Add int32->int16 requantiation for xtensa.
  tensorflow/lite/micro/kernels/xtensa/quantize.cc
Labels: ci:ready_to_merge

#816 Fix error in int32->int16 quantize on xtensa.
  tensorflow/lite/micro/kernels/xtensa/quantize.cc
Labels: ci:ready_to_merge

#817 Move generated array size above generated array
  tensorflow/lite/micro/tools/generate_cc_arrays.py
Labels: ci:ready_to_merge

#820 Have the ability to apply multiple patches.
  tensorflow/lite/micro/tools/make/bash_helpers.sh
  tensorflow/lite/micro/tools/make/ext_libs/xtensa_download.sh
  tensorflow/lite/micro/tools/make/flatbuffers_download.sh
  tensorflow/lite/micro/tools/make/kissfft_download.sh
  tensorflow/lite/micro/tools/make/pigweed_download.sh
  tensorflow/lite/micro/tools/make/renode_download.sh
  tensorflow/lite/micro/tools/make/sifive_sdk_download.sh
Labels: ci:ready_to_merge

#821 Add optimized xtensa leaky relu kernel
  tensorflow/lite/micro/kernels/xtensa/leaky_relu.cc
  tensorflow/lite/micro/tools/ci_build/test_xtensa_hifi3z.sh
Labels: ci:ready_to_merge

#826 Convert concatenation op to use TfLiteEvalTensor
  tensorflow/lite/micro/kernels/concatenation.cc
Labels: ci:ready_to_merge

#824 Update bazel version in the install script
  ci/install_bazel.sh
Labels: ci:ready_to_merge

#799 Added CONV2D and DEPTHWISE_CONV2D optimizations for the Vision P6
  tensorflow/lite/micro/examples/person_detection/person_detection_test.cc
  tensorflow/lite/micro/kernels/xtensa/conv.cc
  tensorflow/lite/micro/kernels/xtensa/conv_hifi.cc
  tensorflow/lite/micro/kernels/xtensa/conv_vision.cc
  tensorflow/lite/micro/kernels/xtensa/depthwise_conv.cc
  tensorflow/lite/micro/kernels/xtensa/depthwise_conv_hifi.cc
  tensorflow/lite/micro/kernels/xtensa/depthwise_conv_vision.cc
  tensorflow/lite/micro/kernels/xtensa/xtensa.h
  tensorflow/lite/micro/kernels/xtensa/xtensa_conv.h
  tensorflow/lite/micro/kernels/xtensa/xtensa_depthwise_conv.h
  tensorflow/lite/micro/tools/ci_build/test_xtensa_vision_p6.sh
  tensorflow/lite/micro/tools/make/ext_libs/xtensa.inc
  tensorflow/lite/micro/tools/make/ext_libs/xtensa_download.sh
Labels: ci:ready_to_merge

#828 Remove logic needed for makefile based project generation.
  tensorflow/lite/micro/examples/magic_wand/Makefile.inc
  tensorflow/lite/micro/examples/micro_speech/Makefile.inc
  tensorflow/lite/micro/tools/make/Makefile
Labels: ci:ready_to_merge

#829 Add dilation support for CMSIS-NN optimized kernels
  tensorflow/lite/micro/kernels/cmsis_nn/conv.cc
  tensorflow/lite/micro/kernels/cmsis_nn/depthwise_conv.cc
  tensorflow/lite/micro/tools/make/ext_libs/cmsis_download.sh
Labels: ci:ready_to_merge

#825 Add @deqiangc as a CODEOWNER for the CI directories.
  CODEOWNERS
Labels: ci:ready_to_merge

#833 Update flatbuffer version to include changes from https://github.com/google/flatbuffers/pull/7003
  tensorflow/lite/micro/tools/make/flatbuffers_download.sh
  tensorflow/lite/micro/tools/make/flatbuffers_temporary.patch
Labels: ci:ready_to_merge
