Repository tensorflow/tflite-micro, pull requests merged in 2021-05, with the labels that each got.

#59 Do not remove ci:run label from the sync PRs.
  .github/workflows/sync.yml
Labels: cla: yes

#61 attempting to use the TFLM-bot account for sync.
  .github/workflows/sync.yml
Labels: cla: yes

#62 Adding a comment to introduce a diff between upstream TF and this repo.
  tensorflow/lite/micro/micro_interpreter.h
Labels: cla: yes

#68 Proper handling of cla labels as part of sync from upstream TF.
  .github/workflows/sync.yml
  README.md
Labels: cla: yes

#74 Add @njeffrie to global codeowners
  CODEOWNERS
Labels: cla: yes

#73 Allow for differences in internal and external bzl rules.
  tensorflow/extra_rules.bzl
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/testing/BUILD
Labels: ci:run, cla: yes

#77 patch TFLM visibility updates from #73 prior to sync from upstream TF.
  ci/sync_from_upstream_tf.sh
  ci/temp_patches/tf_update_visibility.patch
Labels: ci:run, cla: yes

#78 Add link to githubstatus.com
  README.md
Labels: cla: yes

#82 Testing github container registry.
  .github/workflows/ghcr_test.yml
Labels: ci:test, cla: yes

#83 Fix typos in the ghcr_test.yml file.
  .github/workflows/ci.yml
  .github/workflows/ghcr_test.yml
Labels: ci:run, ci:test, cla: yes

#88 Visibility patch for the testing code is no longer needed.
  ci/temp_patches/tf_update_visibility.patch
Labels: ci:run, cla: yes

#98 Change codeowners to be all memembers of @tensorflow/micro
  CODEOWNERS
Labels: cla: yes

#97 Port TFL kernel Gather to TFL Micro
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/gather.cc
  tensorflow/lite/micro/kernels/gather_test.cc
  tensorflow/lite/micro/kernels/micro_ops.h
  tensorflow/lite/micro/micro_mutable_op_resolver.h
  tensorflow/lite/micro/tools/make/Makefile
Labels: ci:run, cla: yes

#99 Clean up of the workflow files.
  .github/workflows/ci.yml
  .github/workflows/sync.yml
Labels: ci:run, cla: yes

#105 Update Xtensa and Antmicro Arduino badges.
  README.md
Labels: cla: yes

#106 Update contributing.md
  CONTRIBUTING.md
  README.md
Labels: cla: yes
