Repository tensorflow/tflite-micro, pull requests merged in 2022-02, with the labels that each got.

#891 Fix yapf version in docker container
  ci/Dockerfile.micro
Labels: ci:ready_to_merge

#901 Remove duplicated tanh int8 test and correct name
  tensorflow/lite/micro/kernels/tanh_test.cc
Labels: ci:ready_to_merge

#893 Convert Colab hello_world training to local Python script
  tensorflow/lite/micro/examples/hello_world/train/compare_models.sh
  tensorflow/lite/micro/examples/hello_world/train/train_hello_world_model.py
Labels: bug, ci:ready_to_merge

#904 Tensorflow now requires version 5.0.0.
  ci/install_bazel.sh
Labels: ci:ready_to_merge

#897 Correct compiler flags to use CCFLAGS for .c and .S files instead of
  tensorflow/lite/micro/tools/make/Makefile
Labels: ci:ready_to_merge

#896 Reshape op - replace slow byte-wise copy with memcpy()
  tensorflow/lite/micro/kernels/reshape.cc
Labels: ci:ready_to_merge

#905 Fix unreachable code flagged during sync to Google3
  tensorflow/lite/micro/kernels/softmax_common.cc
Labels: ci:run, ci:ready_to_merge

#906 Enforce the pairing of AllocateTempXxx and DeallocateTemp api in all kernels
  tensorflow/lite/micro/kernels/add_n.cc
  tensorflow/lite/micro/kernels/cmsis_nn/fully_connected.cc
  tensorflow/lite/micro/kernels/cmsis_nn/svdf.cc
  tensorflow/lite/micro/kernels/fully_connected.cc
  tensorflow/lite/micro/kernels/kernel_runner.cc
  tensorflow/lite/micro/kernels/squeeze.cc
  tensorflow/lite/micro/kernels/squeeze_test.cc
  tensorflow/lite/micro/kernels/strided_slice.cc
  tensorflow/lite/micro/kernels/strided_slice_test.cc
  tensorflow/lite/micro/kernels/transpose.cc
  tensorflow/lite/micro/kernels/xtensa/conv_hifi.cc
  tensorflow/lite/micro/kernels/xtensa/depthwise_conv_hifi.cc
  tensorflow/lite/micro/kernels/xtensa/fully_connected.cc
  tensorflow/lite/micro/kernels/xtensa/pooling.cc
  tensorflow/lite/micro/kernels/xtensa/softmax_int8_int16.cc
  tensorflow/lite/micro/kernels/zeros_like.cc
  tensorflow/lite/micro/test_helpers.cc
Labels: ci:ready_to_merge

#899 Enable nightly run of binary size report
  .github/workflows/log_binary_size.yml
Labels: ci:ready_to_merge

#908 Temporarily disable the global default enforcement of pairing of AllocateTempXxx/DeallocateTemp
  tensorflow/lite/micro/kernels/kernel_runner.cc
  tensorflow/lite/micro/kernels/xtensa/svdf.cc
Labels: ci:ready_to_merge

#917 Update Arm Ethos-U driver
  tensorflow/lite/micro/kernels/ethos_u/README.md
  tensorflow/lite/micro/kernels/ethos_u/ethosu.cc
  tensorflow/lite/micro/tools/make/ext_libs/ethos_u.inc
  tensorflow/lite/micro/tools/make/targets/cortex_m_corstone_300_makefile.inc
  tensorflow/lite/micro/tools/make/third_party_downloads.inc
Labels: ci:ready_to_merge

#922 Enable hifi4 internal tests for Fusion F1 core
  tensorflow/lite/micro/tools/ci_build/test_xtensa_fusion_f1.sh
Labels: ci:ready_to_merge

#928 Update CMSIS-NN fully connected kernel
  tensorflow/lite/micro/kernels/cmsis_nn/fully_connected.cc
Labels: ci:ready_to_merge

#924 Support building custom ops
  tensorflow/lite/micro/tools/make/Makefile
Labels: ci:ready_to_merge

#926 Add tensor_utils header files from TensorFlow Lite
  ci/tflite_files.txt
Labels: ci:ready_to_merge

#931 Add badge for Texa Instruments examples repo (PR #683)
  README.md
Labels: ci:ready_to_merge

#933 Add source and header files for Xtensa FFT optimizations (if they exist)
  tensorflow/lite/micro/tools/make/ext_libs/xtensa.inc
Labels: ci:ready_to_merge

#934 Add context_util.h to file list to sync from tensorflow
  ci/tflite_files.txt
Labels: ci:ready_to_merge

#935 common.c is renamed to common.cc in upstream
  ci/tflite_files.txt
Labels: ci:ready_to_merge

#937 Enforce the pairing of AllocateTempXxx/DeallocateTemp in svdf op
  tensorflow/lite/micro/kernels/svdf_test.cc
  tensorflow/lite/micro/kernels/xtensa/svdf.cc
Labels: ci:ready_to_merge

#938 Sync from upstream after updating the sync file list
  ci/tflite_files.txt
  tensorflow/lite/BUILD
  tensorflow/lite/builtin_op_data.h
  tensorflow/lite/builtin_ops.h
  tensorflow/lite/c/common.cc
  tensorflow/lite/c/common.h
  tensorflow/lite/context_util.h
  tensorflow/lite/kernels/BUILD
  tensorflow/lite/kernels/internal/portable_tensor_utils.h
  tensorflow/lite/kernels/internal/reference/batch_matmul.h
  tensorflow/lite/kernels/internal/reference/integer_ops/fully_connected.h
  tensorflow/lite/kernels/internal/reference/lstm_cell.h
  tensorflow/lite/kernels/internal/reference/portable_tensor_utils.h
  tensorflow/lite/kernels/kernel_util.cc
  tensorflow/lite/kernels/kernel_util.h
Labels: ci:ready_to_merge

#939 Use HIFI4_COPTS for Fusion F1 targets
  tensorflow/lite/micro/kernels/BUILD
Labels: ci:ready_to_merge

#932 Copy flatbuffer alignment tool to open source.
  tensorflow/lite/micro/tools/BUILD
  tensorflow/lite/micro/tools/tflite_flatbuffer_align.cc
Labels: ci:ready_to_merge
