Repository tensorflow/tflite-micro, pull requests merged in 2024-02, with the labels that each got.

#2447 RISC-V target makefile: make the arch, abi and mcmodel configurable.
  tensorflow/lite/micro/tools/make/targets/riscv32_generic_makefile.inc
Labels: ci:ready_to_merge

#2446 Update CMSIS-NN CONV and LSTM implementations
  tensorflow/lite/micro/kernels/cmsis_nn/conv.cc
  tensorflow/lite/micro/kernels/cmsis_nn/fully_connected.cc
  tensorflow/lite/micro/kernels/cmsis_nn/svdf.cc
  tensorflow/lite/micro/kernels/cmsis_nn/unidirectional_sequence_lstm.cc
  tensorflow/lite/micro/kernels/unidirectional_sequence_lstm_test.cc
  tensorflow/lite/micro/tools/make/ext_libs/cmsis_nn.inc
  tensorflow/lite/micro/tools/make/ext_libs/cmsis_nn_download.sh
  tensorflow/lite/micro/tools/make/targets/cortex_m_corstone_300_makefile.inc
Labels: ci:ready_to_merge

#2451 Generic Benchmark Tool changes
  tensorflow/lite/micro/tools/benchmarking/Makefile.inc
  tensorflow/lite/micro/tools/benchmarking/README.md
  tensorflow/lite/micro/tools/benchmarking/generic_model_benchmark.cc
  tensorflow/lite/micro/tools/generate_cc_arrays.py
Labels: bug, ci:ready_to_merge

#2453 Remove initialized but unused variables.
  tensorflow/lite/micro/kernels/xtensa/lstm_eval_hifi.cc
  tensorflow/lite/micro/kernels/xtensa/sub.cc
Labels: ci:ready_to_merge

#2456 Remove unused variables in Xtensa implmenetation of LSTM.
  tensorflow/lite/micro/kernels/xtensa/lstm_eval.cc
Labels: ci:ready_to_merge

#2457 Fix broken hifi3 NDSP lib patch file
  tensorflow/lite/micro/tools/make/ext_libs/ndsplib-hifi3.patch
Labels: ci:ready_to_merge

#2458 Fix a linker error: undefined kMaxBufferCount
  tensorflow/lite/micro/memory_planner/linear_memory_planner.cc
Labels: ci:ready_to_merge

#2460 Fix Corstone Ethos-U CI failure
  .github/workflows/cortex_m.yml
  .github/workflows/tests_post.yml
  tensorflow/lite/micro/tools/make/ext_libs/person_detection_int8_vela_convert.sh
Labels: bug, ci:ready_to_merge

#2462 Add missing micro_context dependency
  tensorflow/lite/micro/tools/benchmarking/BUILD
Labels: ci:ready_to_merge

#2466 Add workflow_call to cortex_m.yml
  .github/workflows/cortex_m.yml
Labels: ci:run_full

#2465 Disable per channel quantization for FC layers
  tensorflow/lite/micro/testing/generate_test_models.py
  tensorflow/lite/micro/tools/requantize_flatbuffer_test.py
Labels: ci:ready_to_merge

#2396 Replace tensorflow-cpu usage with tensorflow
  WORKSPACE
  python/tflite_micro/BUILD
  python/tflite_micro/signal/BUILD
  python/tflite_micro/signal/utils/BUILD
  tensorflow/lite/micro/examples/hello_world/BUILD
  tensorflow/lite/micro/examples/hello_world/quantization/BUILD
  tensorflow/lite/micro/examples/micro_speech/BUILD
  tensorflow/lite/micro/examples/mnist_lstm/BUILD
  tensorflow/lite/micro/examples/person_detection/utils/BUILD
  tensorflow/lite/micro/examples/recipes/BUILD
  tensorflow/lite/micro/integration_tests/BUILD
  tensorflow/lite/micro/kernels/testdata/BUILD
  tensorflow/lite/micro/python/tflite_size/tests/BUILD
  tensorflow/lite/micro/testing/BUILD
  tensorflow/lite/micro/tools/BUILD
  tensorflow/lite/micro/tools/gen_micro_mutable_op_resolver/BUILD
  tensorflow/lite/python/BUILD
  tensorflow/lite/tools/BUILD
  third_party/python_requirements.in
  third_party/python_requirements.txt
Labels: ci:ready_to_merge

#2469 cmsis-nn: update fully connected int8
  tensorflow/lite/micro/kernels/cmsis_nn/fully_connected.cc
  tensorflow/lite/micro/tools/make/ext_libs/cmsis_nn_download.sh
Labels: ci:ready_to_merge

#2408 Add kernel build flag for prioritizing speed or size
  tensorflow/lite/micro/docs/optimized_kernel_implementations.md
  tensorflow/lite/micro/kernels/cmsis_nn/README.md
  tensorflow/lite/micro/kernels/cmsis_nn/transpose_conv.cc
  tensorflow/lite/micro/tools/make/Makefile
Labels: ci:ready_to_merge

#2468 Fix array out-of-bounds access in WideDynamicFuncLut
  python/tflite_micro/signal/utils/wide_dynamic_func_lut_wrapper.cc
Labels: ci:ready_to_merge

#2477 Use absl::Status instead of tsl::Status
  signal/tensorflow_core/ops/delay_op.cc
  signal/tensorflow_core/ops/energy_op.cc
  signal/tensorflow_core/ops/fft_ops.cc
  signal/tensorflow_core/ops/filter_bank_ops.cc
  signal/tensorflow_core/ops/framer_op.cc
  signal/tensorflow_core/ops/overlap_add_op.cc
  signal/tensorflow_core/ops/pcan_op.cc
  signal/tensorflow_core/ops/stacker_op.cc
  signal/tensorflow_core/ops/window_op.cc
Labels: ci:ready_to_merge

#2476 Fix a linker error: undefined kMaxSmallSize
  tensorflow/lite/kernels/internal/runtime_shape.cc
Labels: ci:ready_to_merge

#2484 Prevent runtime_shape.cc removal during sync
  ci/sync_from_upstream_tf.sh
Labels: ci:ready_to_merge

#2482 Remove experimental flag for per-channel FC quantization
  tensorflow/lite/micro/tools/requantize_flatbuffer_test.py
Labels: ci:ready_to_merge
